// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function FetchModels(arg1:app.Config):Promise<app.ModelsResult>;

export function GetConfig():Promise<app.Config>;

export function GetStatus():Promise<app.StatusDTO>;

export function GetUsage():Promise<app.UsageDTO>;

export function RestoreOfficialEnvironment():Promise<void>;

export function SaveConfig(arg1:app.Config):Promise<void>;

export function SetupSystem():Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestConnection(arg1:app.Config):Promise<app.TestResult>;
