// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchModels(arg1) {
  return window['go']['app']['App']['FetchModels'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetUsage() {
  return window['go']['app']['App']['GetUsage']();
}

export function PurgeAllHostsHijacks() {
  return window['go']['app']['App']['PurgeAllHostsHijacks']();
}

export function RestoreOfficialEnvironment() {
  return window['go']['app']['App']['RestoreOfficialEnvironment']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SetupSystem() {
  return window['go']['app']['App']['SetupSystem']();
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}
